DEFAULTS = {
    "CONFIG_VERSION": 1,
    "USER_ID": "",
    "ROOM_ID": "lobby",
    "MODE": "lan",
    "ZMQ_HOST": "127.0.0.1",
    "ZMQ_PORT": 5555,
    "UDP_PORT": 5000,
    "UDP_CHAT_PORT": 5001,
    "BROADCAST_IP": "192.168.100.255",
    "TZ": "Asia/Seoul",
    "TOPMOST_DEFAULT": False,
    "TOPMOST_ON_NOTIFY": True,
    "TOPMOST_ON_NOTIFY_MS": 3000,
    "AUTO_OPEN_DM": True,
    "AUTO_FOCUS_ON_DM": "mention",
    "SOUND_ON_DM": True,
    "SEQ_GAP_WAIT_MS": 300,
    "LOG_LEVEL": "INFO",
}
