DEFAULTS = {
    "CONFIG_VERSION": 1,
    "USER_ID": "",
    "ROOM_ID": "lobby",
    "MODE": "lan",
    "ZMQ_HOST": "127.0.0.1",
    "ZMQ_PORT": 5555,
    "UDP_PORT": 5000,
    "UDP_CHAT_PORT": 5001,
    "UDP_DM_PORT": 5003,
    "BROADCAST_IP": "192.168.100.255",
    "TZ": "Asia/Seoul",
    "TOPMOST_DEFAULT": False,
    "TOPMOST_ON_NOTIFY": True,
    "TOPMOST_ON_NOTIFY_MS": 3000,
    "AUTO_OPEN_DM": True,
    "AUTO_FOCUS_ON_DM": "mention",
    "SOUND_ON_DM": True,
    "SEQ_GAP_WAIT_MS": 300,
    "LOG_LEVEL": "INFO",
    # 서버 관련 설정
    "SERVER_ENABLED": True,
    "SERVER_HOST": "127.0.0.1",
    "SERVER_HTTP_PORT": 8080,
    "SERVER_UDP_PORT": 5002,
    "SERVER_DB_PATH": "tipoff.db",
    "LOAD_HISTORY_ON_START": True,
    "HISTORY_LIMIT": 50,
}
